[2024-08-26 23:00:33,543] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_postgres.crear_schema_postgres manual__2024-08-26T23:00:32.741879+00:00 [queued]>
[2024-08-26 23:00:33,546] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_postgres.crear_schema_postgres manual__2024-08-26T23:00:32.741879+00:00 [queued]>
[2024-08-26 23:00:33,546] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-08-26 23:00:33,547] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2024-08-26 23:00:33,547] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-08-26 23:00:33,552] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): crear_schema_postgres> on 2024-08-26 23:00:32.741879+00:00
[2024-08-26 23:00:33,554] {standard_task_runner.py:52} INFO - Started process 189 to run task
[2024-08-26 23:00:33,556] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_con_conexion_postgres', 'crear_schema_postgres', 'manual__2024-08-26T23:00:32.741879+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag-postgres.py', '--cfg-path', '/tmp/tmpuha7g_yc', '--error-file', '/tmp/tmpha8kd6s1']
[2024-08-26 23:00:33,557] {standard_task_runner.py:80} INFO - Job 12: Subtask crear_schema_postgres
[2024-08-26 23:00:33,585] {task_command.py:371} INFO - Running <TaskInstance: dag_con_conexion_postgres.crear_schema_postgres manual__2024-08-26T23:00:32.741879+00:00 [running]> on host 419b05bd8ee5
[2024-08-26 23:00:33,615] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=FerSoriano
AIRFLOW_CTX_DAG_ID=dag_con_conexion_postgres
AIRFLOW_CTX_TASK_ID=crear_schema_postgres
AIRFLOW_CTX_EXECUTION_DATE=2024-08-26T23:00:32.741879+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-08-26T23:00:32.741879+00:00
[2024-08-26 23:00:33,619] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-08-26 23:00:33,634] {dbapi.py:231} INFO - Running statement: 
            CREATE SCHEMA IF NOT EXISTS *** AUTHORIZATION ***;
        , parameters: None
[2024-08-26 23:00:33,635] {postgres.py:94} INFO - NOTICE:  schema "***" already exists, skipping

[2024-08-26 23:00:33,642] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=dag_con_conexion_postgres, task_id=crear_schema_postgres, execution_date=20240826T230032, start_date=20240826T230033, end_date=20240826T230033
[2024-08-26 23:00:33,655] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-08-26 23:00:33,675] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
